# Generated by Django 5.1.2 on 2024-10-24 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Amazon Brand')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('asin', models.CharField(max_length=50, verbose_name='ASIN')),
                ('sku', models.CharField(max_length=50, verbose_name='Stock Keeping Unit')),
                ('image', models.URLField(verbose_name='URL of the Product Image')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_scraper.brand')),
            ],
        ),
    ]
